#!/usr/bin/env python3
"""Build site/assets/js/outlines.js (country silhouettes for GeoTrace) from a world TopoJSON.

Source data: Natural Earth (public domain) as packaged in the `world-atlas` npm package,
file countries-110m.json (download it once, keep it OUTSIDE the repo).

Usage: python3 scripts/build_outlines.py /path/to/countries-110m.json

Each GeoTrace country becomes [width, height, "path"] on a 100-unit box. Only a country's main
landmass (plus nearby sizeable islands) is kept so far-flung territories don't shrink the shape.
"""
import json, math, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "site" / "assets" / "js" / "outlines.js"
COUNTRIES_JS = ROOT / "site" / "assets" / "js" / "countries.js"
# GeoTrace display name -> name used in the map data (when they differ)
TOPO = {
    "United States": "United States of America", "Democratic Republic of the Congo": "Dem. Rep. Congo",
    "Dominican Republic": "Dominican Rep.", "Bosnia and Herzegovina": "Bosnia and Herz.",
    "North Macedonia": "Macedonia", "Ivory Coast": "Côte d'Ivoire", "South Sudan": "S. Sudan",
}
MIN_AREA = 0.03      # keep islands/exclaves at least 3% the size of the main landmass...
MAX_DIST = 35        # ...and within 35 degrees of it
ARCTIC = 74          # ...and never Arctic archipelagos (e.g. Svalbard)


def decode(topo):
    sx, sy = topo["transform"]["scale"]; tx, ty = topo["transform"]["translate"]
    arcs = []
    for a in topo["arcs"]:
        x = y = 0; pts = []
        for dx, dy in a:
            x += dx; y += dy; pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)
    return arcs


def ring(arcs, idxs):
    pts = []
    for i in idxs:
        seg = arcs[i] if i >= 0 else arcs[~i][::-1]
        pts.extend(seg if not pts else seg[1:])
    return pts


def area(r):
    return abs(sum(r[i][0] * r[(i + 1) % len(r)][1] - r[(i + 1) % len(r)][0] * r[i][1] for i in range(len(r)))) / 2


def centroid(r):
    return sum(p[0] for p in r) / len(r), sum(p[1] for p in r) / len(r)


def polygons(geom, arcs):
    polys = geom["arcs"] if geom["type"] == "MultiPolygon" else [geom["arcs"]]
    return [[ring(arcs, r) for r in poly] for poly in polys]  # each poly: [outer, holes...]


def build(topo_path):
    topo = json.load(open(topo_path)); arcs = decode(topo)
    geoms = {g["properties"]["name"]: g for g in topo["objects"]["countries"]["geometries"]}
    names = re.findall(r"C\('((?:[^'\\]|\\.)*)'", COUNTRIES_JS.read_text())
    out, missing = {}, []
    for name in names:
        g = geoms.get(TOPO.get(name, name))
        if not g: missing.append(name); continue
        polys = polygons(g, arcs)
        # Countries that straddle the antimeridian (Russia, Fiji): unwrap longitudes.
        lons = [p[0] for poly in polys for p in poly[0]]
        if min(lons) < -100 and max(lons) > 100:
            polys = [[[(x + 360 if x < 0 else x, y) for x, y in r] for r in poly] for poly in polys]
        main = max(polys, key=lambda p: area(p[0])); ma = area(main[0]); mc = centroid(main[0])
        keep = [p for p in polys if p is main or (area(p[0]) >= ma * MIN_AREA and centroid(p[0])[1] < ARCTIC and max(abs(centroid(p[0])[0] - mc[0]), abs(centroid(p[0])[1] - mc[1])) <= MAX_DIST)]
        allpts = [pt for p in keep for r in p for pt in r]
        mid = (min(p[1] for p in allpts) + max(p[1] for p in allpts)) / 2
        k = math.cos(math.radians(mid))
        proj = lambda x, y: (x * k, -y)
        xs = [proj(*p)[0] for p in allpts]; ys = [proj(*p)[1] for p in allpts]
        x0, y0, w, h = min(xs), min(ys), max(xs) - min(xs), max(ys) - min(ys)
        s = 100 / max(w, h)
        d = ""
        for p in keep:
            for r in p:
                q = [((proj(*pt)[0] - x0) * s, (proj(*pt)[1] - y0) * s) for pt in r]
                d += "M" + " ".join(f"{x:.1f} {y:.1f}" for x, y in q) + "Z"
        out[name] = [round(w * s, 1), round(h * s, 1), d]
    return out, missing


if __name__ == "__main__":
    data, missing = build(sys.argv[1])
    OUT.write_text("// Country silhouettes for GeoTrace: [width, height, SVG path] on a 100-unit box.\n"
                   "// Generated by scripts/build_outlines.py from Natural Earth data (public domain).\n"
                   "export const OUTLINES = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(data)} outlines, {OUT.stat().st_size // 1024} KB")
    if missing: print("no outline for:", ", ".join(missing))
